// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBITe6Yuzh0SCw6AFhQbhg53njJbpwOVzA',
    appId: '1:690490364095:android:9341f18bc6dd45fb23f60a',
    messagingSenderId: '690490364095',
    projectId: 'task-by-st-352ca',
    storageBucket: 'task-by-st-352ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFUpeq_H-C-cuCeUrmpz-mT-B4qEni-M',
    appId: '1:690490364095:ios:1fe703acb33514ee23f60a',
    messagingSenderId: '690490364095',
    projectId: 'task-by-st-352ca',
    storageBucket: 'task-by-st-352ca.firebasestorage.app',
    iosBundleId: 'com.example.videoPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFUpeq_H-C-cuCeUrmpz-mT-B4qEni-M',
    appId: '1:690490364095:ios:1fe703acb33514ee23f60a',
    messagingSenderId: '690490364095',
    projectId: 'task-by-st-352ca',
    storageBucket: 'task-by-st-352ca.firebasestorage.app',
    iosBundleId: 'com.example.videoPlayer',
  );
}
